name: Workflow for DB 
on:
  pull_request:
    branches: [main]

jobs:
  # Label of the container job
  pr-review:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    
    # Service containers to run with `container-job`
    services: 
     mysql: 
      image: mysql:5.7
      env:
          MYSQL_DATABASE: demoDb
          MYSQL_ROOT_PASSWORD: harsh
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3     
      ports:
          - 3306:3306
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS demoDb;" -uroot -pharsh
      - name: Run tests
        run: npm test
        env: 
            DB: demoDb
            USER_NAME: root
            DB_PASSWORD: harsh
            PORT: 3000
            HOST: localhost
      
     