name: Workflow for DB 
on:
  pull_request:
    branches: [main]

jobs:
  # Label of the container job
  pr-review:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    
    # Service containers to run with `container-job`
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Connect to MySQL
        run:  mysql --user=$DB_USER --password=$DB_PASSWORD
      - name: Create DB    
        run:  mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
        env: 
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      - name: Run tests
        run: npm test
        env: 
            DB: demoDb
            USER_NAME: root
            DB_PASSWORD: root
            PORT: 3000
            HOST: localhost
      
     