name: Workflow for DB 
on:
  pull_request:
    types:
      - closed

jobs:
  after_merge:
    if: github.event.pull_request.merged == true
   
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
    
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Debug Secrets
        run: |
          echo "Git User: ${{ secrets.GIT_USER }}"
          echo "DB Password: ${{ secrets.DB_PASSWORD }}"
      - name: Connect to MySQL
        run:  mysql --user=root --password=root
      - name: Create DB    
        run:  mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u $DB_USER -p$DB_PASSWORD
        env: 
          DB_DATABASE: demoDb
          DB_USER: root
          DB_PASSWORD: root

      - name: Zip webapp
        run:  |
          zip -r webapp.zip . -x   ".git/*" ".github/*"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env: 
            DB: demoDb
            USER_NAME: root
            DB_PASSWORD: root
            PORT: 3000
            HOST: localhost
      - name: Authenticate gcloud
        id: auth 
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_JSON}}"
      - name: Setup gcloud 
        uses: google-github-actions/setup-gcloud@v2
      - name: gcloud CLI
        run: gcloud info
      - name: Initialize Packer
        id: init
        if: success()
        run: packer init webappPacker.pkr.hcl
      - name: Format pkr
        id: fmt
        if: success()
        run: packer fmt webappPacker.pkr.hcl
      - name: Validate Packer
        if: success()
        run: packer validate webappPacker.pkr.hcl
      - name: Build Packer
        if: success()
        run: packer build webappPacker.pkr.hcl
    
  
