name: Workflow for PR 
on:
  pull_request:
    branches: [main]

jobs:
  # Label of the container job
  pr-review:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:latest
        # Provide the password for postgres
        env:
          MYSQL_ROOT_PASSWORD: Chocoslam
          MYSQL_DATABASE: demoDb
          MYSQL_USER: root
          MYSQL_PASSWORD: 1234
        ports:
         - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Node.js setup
        run: npm install
      - name: Initialise server
        run: node app.js
        env:
          PORT: 3000
          DATABASE_URL: mysql://root:1234@localhost:3306/demoDb

      - name: Check if server runs
        run: echo "Listening on port 3000"

     