name: Workflow for PR 
on:
  pull_request:
    branches: [main]

jobs:
  # Label of the container job
  pr-review:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    
    # Service containers to run with `container-job`
   

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'
      - name: Node.js setup
        run: npm install
     
      - name: Check if server runs
        run: echo "Listening on port 3000"

     